Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -17,7 +17,7 @@ on:
       DEFCONFIG:
         description: 'Defconfig name'
         required: true
-        default: 'a23_eur_open_defconfig'
+        default: ''
       KSU:
         description: 'Add KernelSU support'
         type: boolean
@@ -26,14 +26,10 @@ on:
         description: 'KernelSU branch'
         required: true
         default: 'main'
-      UPDATE_TOOLCHAIN:
-        description: 'Update toolchain cache'
-        type: boolean
-        default: false
       KCFLAGS_W:
         description: 'Enable KCFLAGS=-w'
         type: boolean
-        default: false
+        default: true
 
 jobs:
   build:
@@ -98,8 +94,22 @@ jobs:
         if [ ! -d ~/.ccache ]; then
           mkdir -p ~/.ccache
         fi
+        # Handel KSU
         if [[ "$KSU" == "true" ]]; then
-          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s ${{ inputs.KSU_BRANCH }}
+          device_defconfig="arch/arm64/configs/${{ inputs.DEVICE_TARGET }}_defconfig"
+          curl -LSs "https://raw.githubusercontent.com/rsuntk/KernelSU/main/kernel/setup.sh" | bash -s "${{ inputs.KSU_BRANCH }}"
+          
+          echo "CONFIG_KSU=y" >> $device_defconfig
+          echo "CONFIG_KSU_DEBUG=n" >> $device_defconfig
+          echo "CONFIG_KSU_TOOLKIT=n" >> $device_defconfig
+          echo "CONFIG_KSU_EXTRAS=n" >> $device_defconfig
+          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=n" >> $device_defconfig
+          
+          # Check if the append was successful
+          if ! grep -q "CONFIG_KSU_TAMPER_SYSCALL_TABLE" "$device_defconfig"; then
+            echo "Bail! Failed to append defconfig"
+            exit 1  # This actually stops the script from continuing
+          fi
         fi
         bash ../build.sh
 
