Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -27,10 +27,26 @@ on:
           - none
           - thin
           - full
+      KSU:
+        description: 'Add KernelSU support'
+        type: boolean
+        default: false
+      KSU_BRANCH:
+        description: 'KernelSU branch'
+        required: true
+        default: 'main'
       KCFLAGS_W:
         description: 'Enable KCFLAGS=-w'
         type: boolean
         default: true
+      SELINUX_MODE:
+        description: 'SELinux mode'
+        required: true
+        default: 'enforcing'
+        type: choice
+        options:
+          - enforcing
+          - permissive
 
 jobs:
   build:
@@ -44,15 +60,8 @@ jobs:
         fetch-depth: 1
 
     - name: Clone kernel source
-      run: |
-        REPO="${{ github.event.inputs.REPO }}"
-        BRANCH="${{ github.event.inputs.BRANCH }}"
-        
-        if [ -z "$BRANCH" ]; then
-          git clone --depth=1 --recursive "https://github.com/$REPO" kernel_root
-        else
-          git clone --depth=1 -b "$BRANCH" --recursive "https://github.com/$REPO" kernel_root
-        fi
+      if: github.event.inputs.UPDATE_TOOLCHAIN != 'true'
+      run: git clone --depth=1 --single-branch -b ${{ github.event.inputs.BRANCH }} --recursive https://github.com/${{ github.event.inputs.REPO }} kernel_root
         
     - name: Cache Toolchain
       id: cache-toolchain
@@ -72,6 +81,7 @@ jobs:
       run: chmod +x ./build.sh && bash ./build.sh --setup-deps
 
     - name: Setup Build Environment
+      if: github.event.inputs.UPDATE_TOOLCHAIN != 'true'
       id: buildKernel
       run: |
         cd kernel_root
@@ -84,10 +94,13 @@ jobs:
         echo "gitsha=$gitsha1" >> $GITHUB_OUTPUT
 
     - name: Fetch Toolchains
-      if: steps.cache-toolchain.outputs.cache-hit != 'true'
+      if: ${{ steps.cache-toolchain.outputs.cache-hit != 'true' || github.event.inputs.UPDATE_TOOLCHAIN == 'true' }}
+      env:
+        UPDATE_TOOLCHAINS: ${{ github.event.inputs.UPDATE_TOOLCHAIN }}
       run: bash ./build.sh --fetch-toolchains
 
     - name: Build Kernel
+      if: github.event.inputs.UPDATE_TOOLCHAIN != 'true'
       env:
         BRANCH: ${{ github.event.inputs.BRANCH }}
         TG_TOKEN: ${{ secrets.BOT_TOKEN }}
@@ -95,12 +108,30 @@ jobs:
         DEVICE_TARGET: ${{ github.event.inputs.DEVICE_TARGET }}
         DEFCONFIG: ${{ github.event.inputs.DEFCONFIG }}
         LTO: ${{ github.event.inputs.LTO }}
+        KSU: ${{ github.event.inputs.KSU }}
         CI_ZIPNAME: "${{ steps.buildKernel.outputs.buildDetails }}.zip"
         KCFLAGS_W: "${{ github.event.inputs.KCFLAGS_W }}"
+        SELINUX_MODE: "${{ github.event.inputs.SELINUX_MODE }}"
       run: |
         cd kernel_root
         if [ ! -d ~/.ccache ]; then
           mkdir -p ~/.ccache
+        fi
+        # Handle KSU
+        if [[ "$KSU" == "true" ]]; then
+          device_defconfig="arch/arm64/configs/${{ inputs.DEFCONFIG }}"
+          curl -LSs "https://raw.githubusercontent.com/blxyzY/KernelSU/main/kernel/setup.sh" | bash -s "${{ inputs.KSU_BRANCH }}"
+          
+          echo "CONFIG_KSU=y" >> $device_defconfig
+          echo "CONFIG_KSU_DEBUG=n" >> $device_defconfig
+          echo "CONFIG_KSU_TOOLKIT=n" >> $device_defconfig
+          echo "CONFIG_KSU_EXTRAS=n" >> $device_defconfig
+          echo "CONFIG_KSU_TAMPER_SYSCALL_TABLE=n" >> $device_defconfig
+          
+          if ! grep -q "CONFIG_KSU_TAMPER_SYSCALL_TABLE" "$device_defconfig"; then
+            echo "Bail! Failed to append defconfig"
+            exit 1
+          fi
         fi
         bash ../build.sh
 
@@ -109,6 +140,7 @@ jobs:
       with:
         name: Kernel-${{ steps.buildKernel.outputs.buildDetails }}
         path: |
+          kernel_root/out/arch/arm64/boot/Image.gz
+          kernel_root/out/.config        path: |
           kernel_root/*.zip
           kernel_root/out/.config
-          
